version: "3.9"

services:
  master:
    image: mariadb:11
    deploy:
      replicas: 1
      update_config:
        order: start-first
        delay: 1s
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
        max_attempts: 2
      # resources:
      #   limits:
      #     cpus: "0.5"
      #     memory: "512M"
    secrets:
      - db_master_paswd
    environment:
      TZ: Asia/Jakarta
      MARIADB_ROOT_PASSWORD_FILE: "/run/secrets/db_master_paswd"
    command:
      - --port=3301
      - --server-id=1
      - --require_secure_transport=ON
      - --ssl
      - --ssl-ca=/etc/my.cnf.d/tls/ca-cert.pem
      - --ssl-cert=/etc/my.cnf.d/tls/master-server-cert.pem
      - --ssl-key=/etc/my.cnf.d/tls/master-server-key.pem
    volumes:
      - /data/mariadb/master:/var/lib/mysql
      - /data/mariadb/tls:/etc/my.cnf.d/tls
      - /data/mariadb/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - /data/mariadb/conf/client.cnf:/etc/mysql/mariadb.cnf.d/client.cnf
      - /data/mariadb/initdb:/docker-entrypoint-initdb.d
      - /etc/secure/mariadb/encryption:/etc/mysql/encryption
    # ports:
    #   - 3301:3301
    networks:
      - mariadb-network

secrets:
  db_master_paswd:
    external: true

networks:
  mariadb-network:
    external: true
