version: "3.9"

services:
  mariadb-cron-backup:
    image: fradelg/mysql-cron-backup
    deploy:
      replicas: 1
      update_config:
        order: start-first
        delay: 1s
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
        max_attempts: 2
    secrets:
      - db_superadmin
      - db_superadmin_paswd
    environment:
      TZ: "Asia/Jakarta"
      MYSQL_PORT: MAXSCALE_PORT_SET
      MYSQL_HOST: "mariadb_maxscale"
      MYSQL_USER_FILE: "/run/secrets/db_superadmin"
      MYSQL_PASS_FILE: "/run/secrets/db_superadmin_paswd"
      MAX_BACKUPS: "4"
      INIT_BACKUP: "0"
      CRON_TIME: "0 */2 * * *" # Run backup every xxx
      MYSQLDUMP_OPTS: "--triggers --events --triggers --routines --single-transaction --quick --lock-tables=false"
      MYSQL_SSL_OPTS: "--ssl-ca=/etc/my.cnf.d/tls/ca-cert.pem --ssl-cert=/etc/my.cnf.d/tls/client-cert.pem --ssl-key=/etc/my.cnf.d/tls/client-key.pem"
    volumes:
      - BACKUP_DIR_SET:/backup SHARED_VOLUME_SET
      - SECURE_DIR_SET/tls:/etc/my.cnf.d/tls
    networks:
      - mariadb-network

secrets:
  db_superadmin:
    external: true
  db_superadmin_paswd:
    external: true

networks:
  mariadb-network:
    external: true
