version: "3.9"

services:
  mariadb-slave1:
    image: mariadb:11
    deploy:
      replicas: 1
      update_config:
        order: start-first
        delay: 1s
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
        max_attempts: 2
      # resources:
      #   limits:
      #     cpus: "0.5"
      #     memory: "512M"
    environment:
      TZ: Asia/Jakarta
      MARIADB_ROOT_PASSWORD: SLAVE1_ROOT_PASSWORD_SET
      MARIADB_DATABASE: test 
    command:
      - --port=3302
      - --server-id=2
      - --require_secure_transport=ON
      - --ssl
      - --ssl-ca=/etc/my.cnf.d/tls/ca-cert.pem
      - --ssl-cert=/etc/my.cnf.d/tls/slave1-server-cert.pem
      - --ssl-key=/etc/my.cnf.d/tls/slave1-server-key.pem
    volumes:
      - /data/mariadb/slave1:/var/lib/mysql
      - /data/mariadb/encryption:/etc/mysql/encryption
      - /var/lib/mariadb/tls:/etc/my.cnf.d/tls
      - /var/lib/mariadb/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - /var/lib/mariadb/conf/client.cnf:/etc/mysql/mariadb.cnf.d/client.cnf
      - /var/lib/mariadb/scripts/initdb:/docker-entrypoint-initdb.d
    ports:
      - 3302:3302
    networks:
      - mariadb-network

networks:
  mariadb-network:
    external: true
