version: "3.9"

services:
  slave1:
    image: mariadb:11
    deploy:
      replicas: 1
      update_config:
        order: start-first
        delay: 1s
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
        max_attempts: 2
      # resources:
      #   limits:
      #     cpus: "0.5"
      #     memory: "512M"
    secrets:
      - db_slave1_paswd ## change me | is unique in every deployment
    environment:
      TZ: Asia/Jakarta
      MARIADB_ROOT_PASSWORD_FILE: "/run/secrets/db_slave1_paswd" ## change me | is unique in every deployment
    command:
      - --port=3302 ## change me | is unique in every deployment
      - --server-id=2 ## change me | is unique in every deployment
      - --require_secure_transport=ON
      - --ssl
      - --ssl-ca=/etc/my.cnf.d/tls/ca-cert.pem
      - --ssl-cert=/etc/my.cnf.d/tls/slave1-server-cert.pem ## change me | is unique in every deployment
      - --ssl-key=/etc/my.cnf.d/tls/slave1-server-key.pem ## change me | is unique in every deployment
    volumes:
      - DATA_DIR_SET/slave1:/var/lib/mysql SHARED_VOLUME_SET ## change me | is unique in every deployment
      - SECURE_DIR_SET/initdb:/docker-entrypoint-initdb.d SHARED_VOLUME_SET
      - SECURE_DIR_SET/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf SHARED_VOLUME_SET
      - SECURE_DIR_SET/conf/client.cnf:/etc/mysql/mariadb.cnf.d/client.cnf SHARED_VOLUME_SET
      - SECURE_DIR_SET/tls:/etc/my.cnf.d/tls SHARED_VOLUME_SET
      - SECURE_DIR_SET/encryption:/etc/mysql/encryption SHARED_VOLUME_SET
    # ports:
    #   - 3302:3302
    networks:
      - mariadb-network

secrets:
  db_slave1_paswd:
    external: true

networks:
  mariadb-network:
    external: true
