version: "3.9"

services:
  mariadb-slave1:
    image: mariadb:lts
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    deploy:
      replicas: 1
      update_config:
        order: start-first
        delay: 1s
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
        max_attempts: 2
      # resources:
      #   limits:
      #     cpus: "0.5"
      #     memory: "512M"
    environment:
      TZ: Asia/Jakarta
      MYSQL_ROOT_PASSWORD: SLAVE1_ROOT_PASSWORD_SET
    volumes:
      - /data/mariadb/slave1:/var/lib/mysql
      - ./conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./conf/client.cnf:/etc/mysql/mariadb.cnf.d/client.cnf:ro
      - ./tls:/etc/my.cnf.d/tls
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - 3302:3302
    networks:
      - mariadb-network

networks:
  mariadb-network:
    external: true
